# https://docs.readthedocs.io/en/latest/config-file/v2.html
version: 2

formats:
  - htmlzip
  - epub

build:
  os: ubuntu-lts-latest
  tools:
    python: 3.10

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - pyside2
        - p-docs
